import os

CHOOSE_ROLE, ENTER_PASSWORD, CHOOSE_SPECIALTY_MENTOR, MENTOR_MENU, EDIT_MATERIALS, EDIT_TESTS = range(6)
ADD_SPECIALTY_NAME = 6
CHOOSE_SPECIALTY_FOR_EDIT = 7
EDIT_MATERIALS_INPUT = 8
CHOOSE_SPECIALTY_FOR_TEST_EDIT = 9
EDIT_TEST_MENU = 10
ADD_TEST_QUESTION = 11
ADD_TEST_OPTIONS = 12
ADD_TEST_CORRECT = 13
EDIT_EXISTING_QUESTION = 14
CHOOSE_EDIT_TYPE = 15
EDIT_QUESTION_TEXT = 16
EDIT_QUESTION_OPTIONS = 17
EDIT_QUESTION_CORRECT = 18
DELETE_QUESTION = 19
CHOOSE_SPECIALTY_EMPLOYEE, HANDLE_TEST_ANSWER = range(20, 22)
CHOOSE_ACTION_AFTER_SPECIALTY = 1234

DATA_FILE = 'data.json'
import os
from dotenv import load_dotenv

load_dotenv()

MENTOR_PASSWORD = os.getenv("ADMIN_PASSWORD")
